name: github repo sync to gitee repo

on:
  # 定时调用，每天0点执行，因为 github 是在国外，所以时间比中国晚8个小时
  schedule:
    - cron: '0 16 * * *'
jobs:
  sync-gitee:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository list exclude private
        id: repo
        uses: yi-Xu-0100/repo-list-generator@v1.1.1
      - name: Mirror the Github repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/roukaixin
          dst: gitee/roukaixin
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          account_type: user
          src_account_type: user
          dst_account_type: user
          clone_style: "ssh"
          black_list: "roukaixin.github.io,FixIt,image-oss,docker_image_pusher,aggregator,gitea,linux"
          debug: false
          static_list: ${{ steps.repo.outputs.repoList_FORK }}

  sync-org-gitee:
    runs-on: ubuntu-latest
    steps:
      - name: Get Organization repository list exclude private
        id: repo
        uses: yi-Xu-0100/repo-list-generator@v1.1.1
        with:
          user: roukaixin-blog
      - name: Mirror the Github Organization to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/roukaixin-blog
          dst: gitee/roukaixin-blog
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          account_type: org
          src_account_type: org
          dst_account_type: org
          clone_style: "ssh"
          black_list: "roukaixin-blog.github.io"
          debug: false
          static_list: ${{ steps.repo.outputs.repoList_FORK }}